"""Add orders timestamps

Revision ID: 6d04d2a9d8dc
Revises: 566311c78b18
Create Date: 2025-04-02 14:32:24.494604

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d04d2a9d8dc"
down_revision: str | None = "566311c78b18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.create_unique_constraint(None, "orders", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")  # type: ignore[arg-type]
    op.drop_column("orders", "updated_at")
    op.drop_column("orders", "created_at")
    # ### end Alembic commands ###
